### PR TITLE
agenda proposal roughed out

### PR DESCRIPTION
**Pull request by mcr**
This also zeros out the charter for now.

### CODE REVIEW

**Comment by cabo** [comment]
So if showing (not discussing) the charter *is* on the agenda, why zero it out?

**Comment by mcr** [comment]
> So if showing (not discussing) the charter _is_ on the agenda, why zero it out?

I think that I got that wrong on the agenda.

**Comment by nwidell** [comment]
if possible I'd like to see a conditional agenda item

if(support&energy) then
  discuss_proto_charter();

so as to use valuable potential "f2f" time to discuss things that might take weeks of email discussion

**Comment by WAvdBeek** [comment]
Hi Michael,

I do not see enums as currently defined as an issue.
What is the issue statement?

Kind Regards,
Wouter

**Comment by cabo** [comment]
I think enums is a code word here for type choices that do more than json-schema-org enums do, one or both of:

— more than just constants, e.g., integer and number ranges
— assigning semantic identifiers to each of the choices

This is what would have been needed to model StartUpCurrentLevel as defined in /sdfObject/Level 

StartUpCurrentLevelPlus = MinimumDeviceValuePermitted 
                        / StartUpCurrentLevel / SetToPreviousValue
StartUpCurrentLevel = 1..254 ; range somewhat arbitrary
MinimumDeviceValuePermitted = 0 ; arbitrary encoding, not semantic
SetToPreviousValue = 255 ; arbitrary encoding, not semantic

(And why is there no MaximumDeviceValuePermitted, or MiddlePointDeviceValuePermitted, or GeometricMiddleDeviceValuePermitted, or more generally PercentDeviceValuePermitted etc.?)

As can be seen above, anyOf can be used to construct these, but is more powerful (e.g., can be nested) and less clearly points out the semantic identifier annotation.

(Having both enum and anyOf is weird to me, but that is the way json-schema-org is, and maybe restricting anyOf a bit is indeed useful.)

Grüße, Carsten

**Pull request merged**
